### ISSUE TITLE
dbt-impala  sql_header issue

### ISSUE THREAD

**Issue by lllong33** [cloudera/dbt-impala#143]
# bug_info
use sql_header or pre_hook appear `Encountered: CREATE CAUSED BY: Exception: Syntax error`; 
from dbt.log view: `Impala adapter: Server connection error`;  
Reason, before must execute: `compute stats tab_nam;`

code file: sql_header_ex1.sql
```sql
{{ config(
  sql_header="show tables;"
) }}
-- Remove the above running normally
select 1 AS c1
```

target/run: impala-shell execute normal, but dbt syntax errors
```sql
show tables;
create view dbt.sql_header_ex1__dbt_tmp as
select 1 AS c1
;
```

# base_info
Core:
  - installed: 1.3.2
  - latest:    1.4.1 - Update available!
Plugins:
  - impala: 1.3.1 - Up to date!
python version: 3.10.6    
os info: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35

**Comment by tovganesh** [comment]
@lllong33  can you try using pre-hook instead of sql_header and see if that works for you?

**Comment by lllong33** [comment]
> @lllong33 can you try using pre-hook instead of sql_header and see if that works for you?

Great! It was successfully solved. The case is as follows.
