### ISSUE TITLE
Materialization: Incremental - Insert+Overwrite: Table already exists 

### ISSUE THREAD

**Issue by lllong33** [cloudera/dbt-impala#147]
I expect the first execution to be CTE and the second execution to be insert overwrite table xxx;
But, an error is displayed in the following figure
- dbt version
- error info
- model info; target/run info
![image](https://user-images.githubusercontent.com/29864358/223057177-3b943e5b-b471-43ee-9595-5f3bc4f32b9d.png)
![image](https://user-images.githubusercontent.com/29864358/223057968-db70d0ec-1491-4a1e-8db0-ac275e44e8b8.png)

**Comment by lllong33** [comment]
2023-03-07 update log:
- schema=dbt success
Get insert overwrite under schema=dbt normally; schema=dw shows an error table already exists. The materialized/incremental_strategy parameter cannot be obtained?

The following figure shows the execute-info: 
![image](https://user-images.githubusercontent.com/29864358/223346570-adcd6d05-fd67-4d33-9738-76af869c22f9.png)
![image](https://user-images.githubusercontent.com/29864358/223346729-8c232423-3d31-43b6-b6c8-653d2c799bc6.png)

**Comment by tovganesh** [comment]
This issue seems related to https://github.com/cloudera/dbt-impala/pull/94 
Probably related to metastore, but not 100% sure.

**Comment by lllong33** [comment]
> This issue seems related to #94 Probably related to metastore, but not 100% sure.


I pulled the edh_error branch, which magically solved the error problem; But the target/run file is not what I need; It seems that the issue remains that materialized='incremental' has not been recognized;
![image](https://user-images.githubusercontent.com/29864358/223591321-3fc1cee4-3d47-4703-9039-31140294dd48.png)

**Comment by lllong33** [comment]
I want the result to be target/run and insert overwrite; When I tried to switch to schema=dbt, it worked as expected; Very weird
![image](https://user-images.githubusercontent.com/29864358/223593539-1bba1c35-3594-4e32-8817-1ebfd94f349f.png)

**Comment by lllong33** [comment]
![image](https://user-images.githubusercontent.com/29864358/224883601-d823e346-00d2-472f-8094-41fd90cf3e81.png)

**Comment by lllong33** [comment]
that the impala adapter could not get all tables( show table in dw), Only 12 tables are retrieved here, resulting in exists_realtion=None. Instead of going insert_overwrite, it goes CTE;

**Comment by lllong33** [comment]
![image](https://user-images.githubusercontent.com/29864358/224953629-0e735cc2-a13e-4b56-b1ca-9503a5424650.png)
@tovganesh Please help me see how to add a parameter to avoid scanning invalid metadata; Now the problem is that dbt's impl.py doesn't seem to pass the identifier

**Comment by lllong33** [comment]
https://github.com/lllong33/dbt-impala/commit/8f0454b812b358891bd4c6fc4eb234d0bcf54ee1
