### ISSUE TITLE
schema change of model with VIEW materialisation runs ALTER TABLE and fails

### ISSUE THREAD

**Issue by sdairs** [cloudera/dbt-impala#16]
Create a model with materialisation VIEW with cols1,2,3

Run the model

Then change the model to cols1,2,3,4

Run the model

It will error stating that you cannot run ALTER TABLE on a VIEW.

We must use ALTER TABLE for TABLE materialisation & ALTER VIEW for VIEW materialisation

```
12:26:51  Runtime Error in model stg_covid__cases (models/staging/covid/stg_covid__cases.sql)
12:26:51    Runtime Error
12:26:51      AnalysisException: ALTER TABLE not allowed on a view: dbt_demo_staging_covid.stg_covid__cases
12:26:51      
```

**Comment by tovganesh** [comment]
The issue here is that list_relation macro calls show tables, which lists both tables and views with out any distinction.

**Comment by tovganesh** [comment]
@sdairs could you check if this PR resolves above issue for you: https://github.com/cloudera/dbt-impala/pull/20

**Comment by sdairs** [comment]
Nice one @tovganesh - fix looks good
