### ISSUE TITLE
column_type override not being honoured for dbt seed

### ISSUE THREAD

**Issue by sdairs** [cloudera/dbt-impala#17]
create a seed with 2 cols

```
country_code,population
ABW,106766
AFE,677243299
AFG,38928341
```

Running `dbt seed` fails due to type `INT` being inferred, but some values are too large for `INT` and require `BIGINT`.

```
12:56:16  Completed with 1 error and 0 warnings:
12:56:16  
12:56:16  Runtime Error in seed ref__populations (seeds/reference/ref__populations.csv)
12:56:16    AnalysisException: Possible loss of precision for target table 'dbt_demo_reference.ref__populations'.
12:56:16    Expression '3332105361' (type: BIGINT) would need to be cast to INT for column 'population'
```

Create a schema.yml for the seed to overrise the inferred type to `BIGINT`

```
version: 2

seeds:
  - name: ref__populations
    description: Worldwide population data by country
    config:
      column_types:
        population: BIGINT
```

Use `dbt seed --full-refresh` to ensure the new schema is used.

```
12:40:25  Runtime Error in seed ref__populations (seeds/reference/ref__populations.csv)
12:40:25    AnalysisException: Target table 'dbt_demo_reference.ref__populations' is incompatible with source expressions.
12:40:25    Expression ''106766'' (type: STRING) is not compatible with column 'population' (type: BIGINT)
12:40:25 
```

Fails as the over ride is not honoured.

Sounds similar to https://github.com/dbt-labs/dbt-spark/issues/139 seen on dbt-spark

**Comment by tovganesh** [comment]
Did some debugging, apparently the table is correctly created, but some issue with the insert:

`create table s3test.ref__populations (country_code string,population BIGINT)
  

          insert into s3test.ref__populations (country_code, population) values
          (%s,%s),(%s,%s),(%s,%s)
`

**Comment by tovganesh** [comment]
https://github.com/cloudera/dbt-impala/pull/18

@sdairs can you verify if the above PR works at your end?

**Comment by sdairs** [comment]
Thanks @tovganesh - works perfectly

**Comment by sdairs** [comment]
Fix has been merged
