### ISSUE TITLE
add adapter to dbt docs's "Available Adapters" page

### ISSUE THREAD

**Issue by dataders** [cloudera/dbt-impala#32]
The [Available Adapters](https://docs.getdbt.com/docs/available-adapters) page is one of the dbt community's most-visited docs pages. It would be of great benefit for first-time visitors to the dbt docs to see:
1. that this adapter is a possible option for using dbt-core, and
2. how many large the dbt ecosystem of support databases is.

https://github.com/dbt-labs/docs.getdbt.com/issues/1489 exists to address this with all as-of-yet undocumented adapters.

We just released [Documenting a new adapter](https://docs.getdbt.com/docs/contributing/documenting-a-new-adapter), a new guide on how to add an adapter to the Available Adapters page. I'd love to see this adapter on that page, so feel free to reach out with any questions/blockers by either replying to this issue, or posting in the #adapter-ecosystem channel of the dbt Community Slack.

Looking forward to the contribution!

**Comment by tovganesh** [comment]
Hi @dataders, Thanks for the heads up. I am mostly finished writing the docs here: https://github.com/dbt-labs/docs.getdbt.com/compare/current...tovganesh:current and am ready to submit this as a PR.
I will check if there are any new guideline changes.

**Comment by dataders** [comment]
> Hi @dataders, Thanks for the heads up. I am mostly finished writing the docs here: [dbt-labs/docs.getdbt.com@current...tovganesh:current](https://github.com/dbt-labs/docs.getdbt.com/compare/current...tovganesh:current) and am ready to submit this as a PR. I will check if there are any new guideline changes.

hell yeah @tovganesh! feel free to open up a draft PR and I can give some feedback on what you have to far

**Comment by tovganesh** [comment]
PR for this: https://github.com/dbt-labs/docs.getdbt.com/pull/1499

**Comment by dataders** [comment]
thanks @tovganesh! there's still a few comments open on https://github.com/dbt-labs/docs.getdbt.com/pull/1499, but I wanted to merge in anyway and get a first draft. The most important action items would be:
- add link to our Slack channel!
- update the config docs to mention there is support for insert_overwrite now for incremental materializations

**Comment by tovganesh** [comment]
Thanks @dataders for the merge. I will update this.
