### ISSUE TITLE
Support for request_pool

### ISSUE THREAD

**Issue by roots4** [cloudera/dbt-impala#93]
Hello, 

Is there a way to specify the request_pool during execution? Or do you plan developing it in the future?

Thank you,
Alex

**Comment by tovganesh** [comment]
Hey Alex,

You may try pre/post dbt hooks (https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook) to submit a set request_pool statement in your model config, something like:
`{{ config(
  pre_hook = "set request_pool='root.medium'"
) }}`

**Comment by tovganesh** [comment]
This issue is addressed in PR: https://github.com/cloudera/dbt-impala/pull/119
